steps:
- name: 'gcr.io/cloud-builders/docker'
  dir: '/CloudRun'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/Crash-GHaun/random-date-app', '.']
- name: 'gcr.io/cloud-builders/docker'
  dir: '/CloudRun'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/Crash-GHaun/random-date-app']
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/Crash-GHaun/random-date-app'
options:
  logging: CLOUD_LOGGING_ONLY